### ISSUE TITLE
Configure single node EC2 w/ Ocean Middelware & IPFS

### ISSUE THREAD

**Issue by Timothy-AthenaProtocol** [Athena-Protocol/OpServe#1]
Develop

1. Setup an EC2. Configure local single node kubernetis. Run ipfs host .
2. Setup operator service
3. Setup provider
4. Provide operator URL in provider

Test & Automate 

1. Query data, algo from provider using REST API
2. Develop admin UI. Need to make wireframes first. Will need Tim's input.
3. Automate the deployment of  operator service and connect with our backend. Additionally it does the REST calls for provider.

**Comment by Timothy-AthenaProtocol** [comment]
"We are at step 3. Hade some dependency issues to be resolved. Thats done. It needs aquaris service whose deployment version in the doc is not working,. found another link in release docs. Figuring out. Can do local deployment also. Have to setup ganache etc..still n that process." - Umesh , Sprinova https://spririnova.dev Monday June 27

**Comment by mihaisc** [comment]
If it's more helpful you can take a look in our barge repo https://github.com/oceanprotocol/barge where everything is configured and running. Also please open a issue if what you found in docs/readme is incorrect/not working

**Comment by umesh-spirinova** [comment]
We have succesfully deployed a C2D environment. Have opened few issues in github ocean marketplace - 
https://github.com/oceanprotocol/market/issues/1619
https://github.com/oceanprotocol/market/issues/1618
